export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_UPDATE_ITEM = "CART_UPDATE_ITEM";

export const CART_CHECKOUT_REQUEST = "CART_CHECKOUT_REQUEST";
export const CART_CHECKOUT_SUCCESS = "CART_CHECKOUT_SUCCESS";
export const CART_CHECKOUT_FAIL = "CART_CHECKOUT_FAIL";
