const data = {
  products: [
    {
      _id: "1",
      name: "Yellow Hoodie",
      category: "hoodie",
      image: "../images/yellow.png",
      price: 65,
      brand: "bumblebee",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Beige Hoodie",
      category: "hoodie",
      image: "../images/beige.png",
      price: 75,
      brand: "bumblebee",
      rating: 7.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "3",
      name: "Black Hoodie",
      category: "hoodie",
      image: "../images/black.png",
      price: 55,
      brand: "raven",
      rating: 9.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Green Beanie",
      category: "beanie",
      image: "../images/greenbeanie.png",
      price: 65,
      brand: "bumblebee",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Grey Beanie",
      category: "beanie",
      image: "../images/greybeanie.png",
      price: 75,
      brand: "bumblebee",
      rating: 7.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "6",
      name: "Red Beanie",
      category: "beanie",
      image: "../images/redbeanie.png",
      price: 55,
      brand: "raven",
      rating: 9.5,
      numReviews: 10,
      countInStock: 8,
    },
  ],
};

export default data;
